appName: app1-nginx
appImage: aksdevopsacr123.azurecr.io/custom2aksnginxapp1
appVersion: 10
appReplicas: 5
containerPort: 80
appSecretname: aksdevopsacr1231597ca22-auth

servicePort: 80
serviceType: LoadBalancer
